menu:
    Archive: /archives/
    Author: https://tanaka.world/about
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-122034388-1

# Copyright Infomation
startyear: 2014

# Date_formats
date_formats:
  archive: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"